---
- name: Copy CA Cert to Host
  copy:
    src: "{{ssl_ca_cert_filepath}}"
    dest: "/var/ssl/private/generation/{{ssl_ca_cert_filepath|basename}}"

- name: Copy Signed Cert to Host
  copy:
    src: "{{ssl_signed_cert_filepath}}"
    dest: /var/ssl/private/generation/signed.crt

- name: Copy Key to Host
  copy:
    src: "{{ssl_key_filepath}}"
    dest: /var/ssl/private/generation/key.pem

- include_tasks: custom_certs_regular.yml
  when: not fips_enabled|bool

- include_tasks: custom_certs_fips.yml
  when: fips_enabled|bool
