---
- name: Create Truststore and Import the CA Cert
  shell: |
    keytool -noprompt -keystore {{truststore_path}} \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file /var/ssl/private/generation/{{ssl_ca_cert_filepath|basename}} \
      -storepass {{truststore_storepass}} \
      -keypass {{truststore_storepass}} \
      -providerpath {{fips_jar_path}} \
      -providerclass {{fips_provider_class}}

- name: Put Key and Signed Cert into pkcs12 Format
  shell: |
    openssl pkcs12 -export \
      -in /var/ssl/private/generation/signed.crt \
      -inkey /var/ssl/private/generation/key.pem \
      -out /var/ssl/private/generation/client.p12 \
      -name kafkassl \
      -passout pass:mykeypassword

- name: Create Keystore
  shell: |
    keytool -importkeystore \
      -srckeystore /var/ssl/private/generation/client.p12 \
      -srcstoretype pkcs12 \
      -srcstorepass mykeypassword \
      -destkeystore {{keystore_path}} \
      -deststoretype pkcs12 \
      -deststorepass {{keystore_storepass}} \
      -destkeypass {{keystore_storepass}} \
      -providerpath {{fips_jar_path}} \
      -providerclass {{fips_provider_class}}

- name: Import the CA Cert into Keystore
  shell: |
    keytool -noprompt -keystore {{keystore_path}} \
      -storetype pkcs12 \
      -keyalg RSA \
      -alias CARoot \
      -import -file /var/ssl/private/generation/{{ssl_ca_cert_filepath|basename}} \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}} \
      -providerpath {{fips_jar_path}} \
      -providerclass {{fips_provider_class}}
